# Generated by Django 3.2 on 2021-04-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='vemac_id',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
    ]
