# Generated by Django 3.2 on 2021-04-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0002_message_vemac_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='vemac_id',
        ),
    ]
