# Generated by Django 3.2 on 2021-04-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0003_remove_message_vemac_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='vemac_id',
            field=models.IntegerField(default=256),
            preserve_default=False,
        ),
    ]
