# Generated by Django 3.2 on 2021-04-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0004_message_vemac_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='course',
            field=models.CharField(blank=True, max_length=10, verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='message',
            name='danger',
            field=models.CharField(blank=True, max_length=5, verbose_name='Danger'),
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.CharField(blank=True, max_length=6, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='message',
            name='lat',
            field=models.CharField(blank=True, max_length=10, verbose_name='Lat'),
        ),
        migrations.AddField(
            model_name='message',
            name='lon',
            field=models.CharField(blank=True, max_length=10, verbose_name='Lon'),
        ),
        migrations.AddField(
            model_name='message',
            name='overlake',
            field=models.CharField(blank=True, max_length=1, verbose_name='Overlake'),
        ),
        migrations.AddField(
            model_name='message',
            name='sats',
            field=models.CharField(blank=True, max_length=10, verbose_name='Sats'),
        ),
        migrations.AddField(
            model_name='message',
            name='speed',
            field=models.CharField(blank=True, max_length=10, verbose_name='Speed'),
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.CharField(blank=True, max_length=8, verbose_name='Time'),
        ),
    ]
